import React, { useState, useRef, useEffect } from 'react';

/* Observation type colors (only types actually generated by hooks) */
const TYPE_CONFIG: Record<string, { color: string; label: string }> = {
  'file-write': { color: 'bg-accent-green', label: 'Changes' },
  'file-read': { color: 'bg-accent-cyan', label: 'Reads' },
  'command': { color: 'bg-accent-amber', label: 'Commands' },
  'research': { color: 'bg-accent-blue', label: 'Research' },
  'delegation': { color: 'bg-accent-violet', label: 'Delegations' },
  'tool-use': { color: 'bg-zinc-400', label: 'Tools' },
};

/* Colori per progetto (hash deterministico) */
const PROJECT_COLORS = [
  { bg: 'bg-accent-violet/15', text: 'text-accent-violet', ring: 'ring-accent-violet/30' },
  { bg: 'bg-accent-blue/15', text: 'text-accent-blue', ring: 'ring-accent-blue/30' },
  { bg: 'bg-accent-green/15', text: 'text-accent-green', ring: 'ring-accent-green/30' },
  { bg: 'bg-accent-amber/15', text: 'text-accent-amber', ring: 'ring-accent-amber/30' },
  { bg: 'bg-accent-rose/15', text: 'text-accent-rose', ring: 'ring-accent-rose/30' },
  { bg: 'bg-accent-cyan/15', text: 'text-accent-cyan', ring: 'ring-accent-cyan/30' },
  { bg: 'bg-accent-orange/15', text: 'text-accent-orange', ring: 'ring-accent-orange/30' },
];

/* Formatta conteggio token in formato leggibile (1.2k, 45.3k, 1.2M) */
function formatTokenCount(tokens: number): string {
  if (tokens >= 1_000_000) return `${(tokens / 1_000_000).toFixed(1)}M`;
  if (tokens >= 1_000) return `${(tokens / 1_000).toFixed(1)}k`;
  return String(tokens);
}

function getProjectColorByName(name: string) {
  let hash = 0;
  for (let i = 0; i < name.length; i++) hash = ((hash << 5) - hash) + name.charCodeAt(i) | 0;
  return PROJECT_COLORS[Math.abs(hash) % PROJECT_COLORS.length];
}

interface SidebarProps {
  projects: string[];
  currentFilter: string;
  onFilterChange: (project: string) => void;
  activeTypes: Set<string>;
  onToggleType: (type: string) => void;
  stats: { observations: number; summaries: number; prompts: number; tokenEconomics: { discoveryTokens: number; readTokens: number; savings: number } };
  getDisplayName: (project: string) => string;
  onRenameProject: (project: string, displayName: string) => Promise<void>;
}

export function Sidebar({
  projects, currentFilter, onFilterChange, activeTypes, onToggleType,
  stats, getDisplayName, onRenameProject,
}: SidebarProps) {
  const [editingProject, setEditingProject] = useState<string | null>(null);
  const [editValue, setEditValue] = useState('');
  const editInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (editingProject && editInputRef.current) {
      editInputRef.current.focus();
      editInputRef.current.select();
    }
  }, [editingProject]);

  const startEditing = (project: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setEditingProject(project);
    setEditValue(getDisplayName(project));
  };

  const confirmEdit = async () => {
    if (editingProject && editValue.trim()) {
      await onRenameProject(editingProject, editValue.trim());
    }
    setEditingProject(null);
  };

  const cancelEdit = () => { setEditingProject(null); setEditValue(''); };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') confirmEdit();
    if (e.key === 'Escape') cancelEdit();
  };

  return (
    <aside className="h-full overflow-y-auto bg-surface-1 border-r border-border flex flex-col">
      {/* Sezione: Progetti */}
      <div className="p-4">
        <h3 className="text-[11px] font-semibold uppercase tracking-wider text-zinc-500 mb-3 px-2">Projects</h3>

        {/* All Projects */}
        <button
          onClick={() => onFilterChange('')}
          className={`w-full flex items-center gap-3 px-3 py-2 rounded-lg text-sm transition-all text-left mb-0.5 ${
            currentFilter === ''
              ? 'bg-accent-violet/10 text-accent-violet font-semibold'
              : 'text-zinc-400 hover:text-zinc-200 hover:bg-surface-2'
          }`}
        >
          <div className="w-7 h-7 rounded-md bg-accent-violet/15 flex items-center justify-center flex-shrink-0">
            <svg className="w-3.5 h-3.5 text-accent-violet" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <rect x="3" y="3" width="7" height="7" /><rect x="14" y="3" width="7" height="7" />
              <rect x="3" y="14" width="7" height="7" /><rect x="14" y="14" width="7" height="7" />
            </svg>
          </div>
          <span className="flex-1">All projects</span>
          <span className="text-xs text-zinc-600 font-mono tabular-nums">{projects.length}</span>
        </button>

        {/* Lista progetti */}
        <div className="flex flex-col gap-0.5 mt-1">
          {projects.map(project => {
            const pc = getProjectColorByName(project);
            const isEditing = editingProject === project;
            const isActive = currentFilter === project;
            const initials = getDisplayName(project).substring(0, 2).toUpperCase();

            return (
              <div key={project} className="group">
                {isEditing ? (
                  <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-surface-3 border border-border">
                    <input
                      ref={editInputRef}
                      type="text"
                      value={editValue}
                      onChange={e => setEditValue(e.target.value)}
                      onKeyDown={handleKeyDown}
                      onBlur={confirmEdit}
                      className="flex-1 min-w-0 bg-transparent border-none outline-none text-sm text-zinc-200"
                    />
                    <button onClick={confirmEdit} className="text-accent-green hover:text-accent-green/80 p-0.5">
                      <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><polyline points="20 6 9 17 4 12" /></svg>
                    </button>
                    <button onClick={cancelEdit} className="text-zinc-500 hover:text-zinc-300 p-0.5">
                      <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="M18 6 6 18M6 6l12 12" /></svg>
                    </button>
                  </div>
                ) : (
                  <button
                    onClick={() => onFilterChange(project)}
                    className={`w-full flex items-center gap-3 px-3 py-2 rounded-lg text-sm transition-all text-left ${
                      isActive
                        ? 'bg-surface-3 text-zinc-100 font-medium'
                        : 'text-zinc-400 hover:text-zinc-200 hover:bg-surface-2'
                    }`}
                  >
                    <div className={`w-7 h-7 rounded-md flex items-center justify-center flex-shrink-0 text-[11px] font-bold ${pc.bg} ${pc.text}`}>
                      {initials}
                    </div>
                    <span className="flex-1 truncate">{getDisplayName(project)}</span>
                    <button
                      type="button"
                      onClick={e => startEditing(project, e)}
                      className="opacity-0 group-hover:opacity-100 text-zinc-600 hover:text-zinc-300 transition-all p-0.5"
                      title="Rename"
                    >
                      <svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
                      </svg>
                    </button>
                  </button>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* Divider */}
      <div className="mx-4 h-px bg-border" />

      {/* Sezione: Filtri tipo */}
      <div className="p-4">
        <h3 className="text-[11px] font-semibold uppercase tracking-wider text-zinc-500 mb-3 px-2">Filters</h3>
        <div className="flex flex-col gap-0.5">
          {Object.entries(TYPE_CONFIG).map(([type, config]) => {
            const isActive = activeTypes.has(type);
            return (
              <label
                key={type}
                className={`flex items-center gap-3 px-3 py-2 rounded-lg text-sm cursor-pointer transition-all ${
                  isActive ? 'text-zinc-300 hover:text-zinc-100' : 'text-zinc-600 hover:text-zinc-400'
                }`}
              >
                <div className={`w-4 h-4 rounded border flex items-center justify-center flex-shrink-0 transition-all ${
                  isActive
                    ? 'bg-accent-violet border-accent-violet'
                    : 'bg-transparent border-zinc-600'
                }`}>
                  {isActive && (
                    <svg className="w-2.5 h-2.5 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
                      <polyline points="20 6 9 17 4 12" />
                    </svg>
                  )}
                </div>
                <input type="checkbox" checked={isActive} onChange={() => onToggleType(type)} className="sr-only" />
                <div className={`w-2.5 h-2.5 rounded-full flex-shrink-0 ${config.color} ${isActive ? 'opacity-100' : 'opacity-30'}`} />
                <span className="flex-1">{config.label}</span>
              </label>
            );
          })}
        </div>
      </div>

      {/* Divider */}
      <div className="mx-4 h-px bg-border" />

      {/* Sezione: Statistiche */}
      <div className="p-4">
        <h3 className="text-[11px] font-semibold uppercase tracking-wider text-zinc-500 mb-3 px-2">Statistics</h3>
        <div className="grid grid-cols-2 gap-2">
          {[
            { label: 'Observations', value: stats.observations, color: 'text-accent-violet' },
            { label: 'Summaries', value: stats.summaries, color: 'text-accent-cyan' },
            { label: 'Prompts', value: stats.prompts, color: 'text-accent-amber' },
            { label: 'Projects', value: projects.length, color: 'text-accent-green' },
          ].map(item => (
            <div key={item.label} className="rounded-lg bg-surface-2 border border-border px-3 py-3 text-center">
              <div className={`text-xl font-bold tabular-nums ${item.color}`}>{item.value}</div>
              <div className="text-[10px] uppercase tracking-wider text-zinc-600 mt-1">{item.label}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Sezione: Token Economics */}
      {(stats.tokenEconomics.discoveryTokens > 0 || stats.tokenEconomics.readTokens > 0) && (
        <>
          <div className="mx-4 h-px bg-border" />
          <div className="p-4">
            <h3 className="text-[11px] font-semibold uppercase tracking-wider text-zinc-500 mb-3 px-2">Token Economics</h3>
            <div className="space-y-2">
              <div className="rounded-lg bg-surface-2 border border-border px-3 py-2.5">
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-[10px] uppercase tracking-wider text-zinc-600">Discovery</span>
                  <span className="text-xs font-bold text-amber-400 tabular-nums">{formatTokenCount(stats.tokenEconomics.discoveryTokens)}</span>
                </div>
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-[10px] uppercase tracking-wider text-zinc-600">Read cost</span>
                  <span className="text-xs font-bold text-cyan-400 tabular-nums">{formatTokenCount(stats.tokenEconomics.readTokens)}</span>
                </div>
                <div className="h-px bg-border my-1.5" />
                <div className="flex items-center justify-between">
                  <span className="text-[10px] uppercase tracking-wider text-zinc-600">Savings</span>
                  <span className="text-xs font-bold text-emerald-400 tabular-nums">{formatTokenCount(stats.tokenEconomics.savings)}</span>
                </div>
              </div>
              {/* Barra visuale del rapporto */}
              {stats.tokenEconomics.discoveryTokens > 0 && (
                <div className="rounded-md overflow-hidden h-2 bg-surface-3">
                  <div
                    className="h-full bg-gradient-to-r from-emerald-500 to-emerald-400 transition-all"
                    style={{ width: `${Math.min(100, Math.round((stats.tokenEconomics.readTokens / stats.tokenEconomics.discoveryTokens) * 100))}%` }}
                  />
                </div>
              )}
              {stats.tokenEconomics.discoveryTokens > 0 && (
                <p className="text-[10px] text-zinc-600 text-center">
                  {Math.round((1 - stats.tokenEconomics.readTokens / stats.tokenEconomics.discoveryTokens) * 100)}% token reduction
                </p>
              )}
            </div>
          </div>
        </>
      )}

      {/* Footer */}
      <div className="mt-auto px-4 py-4 space-y-2">
        <div className="flex items-center justify-center gap-3">
          <a href="https://github.com/auriti-web-design/kiro-memory" target="_blank" rel="noopener noreferrer" className="text-zinc-600 hover:text-zinc-400 transition-colors" title="GitHub">
            <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0 1 12 6.844a9.59 9.59 0 0 1 2.504.337c1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.02 10.02 0 0 0 22 12.017C22 6.484 17.522 2 12 2z"/></svg>
          </a>
          <a href="https://auritidesign.it/docs/kiro-memory/" target="_blank" rel="noopener noreferrer" className="text-zinc-600 hover:text-zinc-400 transition-colors" title="Documentazione">
            <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z" /><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z" /></svg>
          </a>
        </div>
        <div className="text-[10px] text-zinc-700 font-mono text-center">Kiro Memory v1.7.1</div>
      </div>
    </aside>
  );
}
